-- ============================================================
-- CREAZIONE TABELLA VISITE_LOGS PER LOG CALENDARIO
-- Da eseguire nel SQL Editor di Supabase
-- ============================================================

-- 1. Crea la tabella visite_logs
CREATE TABLE IF NOT EXISTS public.visite_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visita_id bigint,  -- ID della visita correlata (nessuna chiave esterna obbligatoria per preservare lo storico se cancellata)
    descrizione text NOT NULL,
    utente text NOT NULL,
    data_ora timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Abilitazione della Row Level Security (RLS)
ALTER TABLE public.visite_logs ENABLE ROW LEVEL SECURITY;

-- 3. Policy di lettura (SELECT) solo per utenti autenticati
DROP POLICY IF EXISTS "Consenti SELECT a utenti autenticati" ON public.visite_logs;
CREATE POLICY "Consenti SELECT a utenti autenticati" 
ON public.visite_logs FOR SELECT 
TO authenticated 
USING (auth.uid() IS NOT NULL);

-- 4. Policy di scrittura (INSERT) solo per utenti autenticati
DROP POLICY IF EXISTS "Consenti INSERT a utenti autenticati" ON public.visite_logs;
CREATE POLICY "Consenti INSERT a utenti autenticati" 
ON public.visite_logs FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() IS NOT NULL);
