-- ========================================================
-- HOMELAB CRM - DATABASE SCHEMA (CLEAN SLATE RESET)
-- ========================================================

-- Drop tables in dependency order
DROP TABLE IF EXISTS visite CASCADE;
DROP TABLE IF EXISTS immobili CASCADE;
DROP TABLE IF EXISTS contatti CASCADE;

-- 1. CREATE TABLE: CONTATTI (Anagrafica clienti, agenti, proprietari)
CREATE TABLE contatti (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cognome text NOT NULL,
    nome text NOT NULL,
    societa text,
    ruolo text NOT NULL,
    telefono text,
    mail text,
    note text,
    created_at timestamptz DEFAULT now()
);

-- 2. CREATE TABLE: IMMOBILI (Portafoglio immobiliare - Minimal Clean Slate)
CREATE TABLE immobili (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome_immobile text NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- 3. CREATE TABLE: VISITE (Attività di calendario, sopralluoghi, visite)
CREATE TABLE visite (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    immobile_id bigint REFERENCES immobili(id) ON DELETE CASCADE,
    data_ora timestamptz NOT NULL,
    tipo_visita text NOT NULL,
    esito text NOT NULL DEFAULT 'NEUTRO',
    feedback text,
    cliente_id bigint REFERENCES contatti(id) ON DELETE SET NULL,
    partecipanti text,
    creato_da text,
    created_at timestamptz DEFAULT now()
);

-- 4. SEED DATA: CONTATTI
INSERT INTO contatti (id, cognome, nome, societa, ruolo, telefono, mail, note) OVERRIDING SYSTEM VALUE VALUES
(1, 'Honchar', 'Olga', 'HOME LAB Real Estate Sagl', 'Agente Immobiliare', '+41 79 533 74 19', 'o.honchar@homelabrealestate.ch', 'Agente principale di riferimento.'),
(2, 'Iannone', 'Andrea', '', 'Proprietario, Locatore', '+41 76 458 29 29', 'a.iannone@exclusive-properties.ch', 'Proprietario.'),
(3, 'Boldi', 'Massimiliano', 'HOME LAB Real Estate Sagl', 'Intermediario', '+41 79 457 95 58', 'm.boldi@homelabrealestate.ch', 'Intermediario.');

SELECT setval(pg_get_serial_sequence('contatti', 'id'), COALESCE(MAX(id), 1)) FROM contatti;

-- 5. SEED DATA: IMMOBILI (Minimal)
INSERT INTO immobili (id, nome_immobile) OVERRIDING SYSTEM VALUE VALUES
(101, 'Villa Vista Lago Bissone'),
(102, 'Attico Prestigioso Lugano');

SELECT setval(pg_get_serial_sequence('immobili', 'id'), COALESCE(MAX(id), 1)) FROM immobili;

-- 6. SEED DATA: VISITE
INSERT INTO visite (id, immobile_id, data_ora, tipo_visita, esito, feedback, cliente_id, partecipanti, creato_da) OVERRIDING SYSTEM VALUE VALUES
(30, 102, '2026-06-18T10:00:00+02:00', 'Visita Cliente', 'NEUTRO', 'Primo incontro conoscitivo sull\'immobile.', 3, 'Massimiliano Boldi, Andrea Iannone', 'MASSIMILIANO BOLDI');

SELECT setval(pg_get_serial_sequence('visite', 'id'), COALESCE(MAX(id), 1)) FROM visite;
