-- ========================================================
-- HOMELAB CRM - DATABASE SCHEMA (CON AUTENTICAZIONE E DETTAGLI COMPLETI)
-- ========================================================

-- Rimozione delle risorse in ordine di dipendenza
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users CASCADE;
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
DROP TABLE IF EXISTS public.visite CASCADE;
DROP TABLE IF EXISTS public.immobili CASCADE;
DROP TABLE IF EXISTS public.contatti CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- 1. Tabella dei profili utente collegata all'autenticazione Supabase
CREATE TABLE public.profiles (
    id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    nome text,
    cognome text,
    ruolo text DEFAULT 'User',
    foto text,
    updated_at timestamptz DEFAULT now(),
    created_at timestamptz DEFAULT now()
);

-- 2. Tabella: CONTATTI (Clienti, Agenti, Proprietari)
CREATE TABLE public.contatti (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cognome text NOT NULL,
    nome text NOT NULL,
    societa text,
    ruolo text[] DEFAULT '{}'::text[],
    telefono text,
    mail text,
    note text,
    note_contatto text,
    immobili_posseduti bigint[] DEFAULT '{}'::bigint[],
    immobili_gestiti bigint[] DEFAULT '{}'::bigint[],
    created_at timestamptz DEFAULT now()
);

-- 3. Tabella: IMMOBILI (Portafoglio Immobiliare Completo)
CREATE TABLE public.immobili (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome_immobile text NOT NULL,
    codice_immobile text NOT NULL,
    immagine_di_riferimento text,
    immobile_in text[],
    stato text,
    mandato_firmato text,
    tipo_di_mandato text,
    mandato text,
    prezzo_di_vendita numeric DEFAULT 0,
    prezzo_di_affitto numeric DEFAULT 0,
    spese_condominiali text,
    costo_parcheggi numeric DEFAULT 0,
    indirizzo text,
    comune text,
    npa integer,
    nazione text DEFAULT 'Svizzera',
    categoria text,
    tipo text[],
    superficie_abitabile integer DEFAULT 0,
    superficie_sul integer DEFAULT 0,
    numero_di_locali numeric(3,1) DEFAULT 0,
    numero_bagni integer DEFAULT 0,
    anno_di_costruzione integer DEFAULT 0,
    ultimo_rinnovo integer DEFAULT 0,
    garage integer DEFAULT 0,
    parcheggio integer DEFAULT 0,
    descrizione_immobile text,
    note_interne text,
    planimetria text,
    link_a_cartella_condivisa text,
    numero_di_mappale text,
    tipo_di_residenza text[],
    vendibile_a_stranieri text,
    estratto_registro_fondiario text,
    estratto_registro_fondiario_doc text,
    descrittivo_tecnico text,
    descrittivo_tecnico_doc text,
    regolamento_condominiale text,
    regolamento_condominiale_doc text,
    spese_condominiali_doc text,
    assicurazione_stabile text,
    assicurazione_stabile_doc text,
    verbale_ultima_assemblea text,
    verbale_ultima_assemblea_doc text,
    fondo_rinnovamento text,
    fondo_rinnovamento_doc text,
    valore_di_stima text,
    valore_di_stima_doc text,
    piano_assegnazioni_parti_comuni text,
    piano_assegnazioni_parti_comuni_doc text,
    rasi text,
    rasi_doc text,
    certificato_radon text,
    certificato_radon_doc text,
    proprietario_id bigint REFERENCES public.contatti(id) ON DELETE SET NULL,
    agente_id bigint REFERENCES public.contatti(id) ON DELETE SET NULL,
    creato_da text,
    ultima_modifica_il text,
    ultima_modifica_fatta_da text,
    created_at timestamptz DEFAULT now()
);

-- 4. Tabella: VISITE (Calendario, Sopralluoghi, Visite)
CREATE TABLE public.visite (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    immobile_id bigint REFERENCES public.immobili(id) ON DELETE CASCADE,
    data_ora timestamptz NOT NULL,
    tipo_visita text NOT NULL,
    esito text NOT NULL DEFAULT 'NEUTRO',
    feedback text,
    cliente_id bigint REFERENCES public.contatti(id) ON DELETE SET NULL,
    partecipanti text,
    creato_da text,
    created_at timestamptz DEFAULT now()
);

-- Abilitazione della Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contatti ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.immobili ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visite ENABLE ROW LEVEL SECURITY;

-- Policy di Sicurezza RLS per l'accesso autenticato
CREATE POLICY "Profili visibili da autenticati" ON public.profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "Modifica profilo personale" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id);

CREATE POLICY "Contatti accessibili da autenticati" ON public.contatti FOR ALL TO authenticated USING (true);
CREATE POLICY "Immobili accessibili da autenticati" ON public.immobili FOR ALL TO authenticated USING (true);
CREATE POLICY "Visite accessibili da autenticati" ON public.visite FOR ALL TO authenticated USING (true);

-- Trigger per l'inserimento del profilo automatico
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, nome, cognome, ruolo)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'nome', ''),
    COALESCE(new.raw_user_meta_data->>'cognome', ''),
    COALESCE(new.raw_user_meta_data->>'ruolo', 'User')
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- SEED DATA: CONTATTI
INSERT INTO public.contatti (id, cognome, nome, societa, ruolo, telefono, mail, note, note_contatto, immobili_posseduti, immobili_gestiti) OVERRIDING SYSTEM VALUE VALUES
(1, 'Honchar', 'Olga', 'HOME LAB Real Estate Sagl', ARRAY['Agente Immobiliare']::text[], '+41 79 533 74 19', 'o.honchar@homelabrealestate.ch', 'Agente principale di riferimento per le proprietà di alto standing a Lugano.', 'Agente principale di riferimento per le proprietà di alto standing a Lugano.', '{}'::bigint[], '{}'::bigint[]),
(2, 'Iannone', 'Andrea', '', ARRAY['Proprietario', 'Locatore']::text[], '+41 76 458 29 29', 'a.iannone@exclusive-properties.ch', 'Proprietario dell''appartamento esclusivo con piscina a Bissone.', 'Proprietario dell''appartamento esclusivo con piscina a Bissone.', '{}'::bigint[], '{}'::bigint[]),
(3, 'Boldi', 'Massimiliano', 'HOME LAB Real Estate Sagl', ARRAY['Acquirente']::text[], '+41 79 457 95 58', 'm.boldi@homelabrealestate.ch', 'Gestore delle relazioni con i clienti e procacciatore d''affari.', 'Gestore delle relazioni con i clienti e procacciatore d''affari.', '{}'::bigint[], '{}'::bigint[]),
(4, 'Cau', 'Stefano', 'Design Addict', ARRAY['Fotografo']::text[], '+41 76 526 28 82', 'studio@designaddict.ch', 'Fotografo professionista specializzato in architettura d''interni e video droni.', 'Fotografo professionista specializzato in architettura d''interni e video droni.', '{}'::bigint[], '{}'::bigint[]),
(5, 'Kogan Amaro', 'Julio', '', ARRAY['Acquirente']::text[], '+41 78 991 12 23', 'j.kogan@vip-invest.ch', 'Potenziale acquirente interessato ad attici di lusso con vista lago.', 'Potenziale acquirente interessato ad attici di lusso con vista lago.', '{}'::bigint[], '{}'::bigint[]);

SELECT setval(pg_get_serial_sequence('public.contatti', 'id'), COALESCE(MAX(id), 1)) FROM public.contatti;

-- SEED DATA: IMMOBILI
INSERT INTO public.immobili (
    id, nome_immobile, codice_immobile, immagine_di_riferimento, immobile_in, stato, mandato_firmato, tipo_di_mandato, mandato,
    prezzo_di_vendita, prezzo_di_affitto, spese_condominiali, costo_parcheggi, indirizzo, comune, npa, nazione, categoria, tipo,
    superficie_abitabile, superficie_sul, numero_di_locali, numero_bagni, anno_di_costruzione, ultimo_rinnovo, garage, parcheggio,
    descrizione_immobile, proprietario_id, agente_id, creato_da, ultima_modifica_il, ultima_modifica_fatta_da,
    planimetria, numero_di_mappale, tipo_di_residenza, vendibile_a_stranieri,
    estratto_registro_fondiario, estratto_registro_fondiario_doc,
    descrittivo_tecnico, descrittivo_tecnico_doc,
    regolamento_condominiale, regolamento_condominiale_doc,
    spese_condominiali_doc,
    assicurazione_stabile, assicurazione_stabile_doc,
    verbale_ultima_assemblea, verbale_ultima_assemblea_doc,
    fondo_rinnovamento, fondo_rinnovamento_doc,
    valore_di_stima, valore_di_stima_doc,
    piano_assegnazioni_parti_comuni, piano_assegnazioni_parti_comuni_doc,
    rasi, rasi_doc,
    certificato_radon, certificato_radon_doc
) OVERRIDING SYSTEM VALUE VALUES
(101, 'ESCLUSIVA PROPRIETÀ VISTA LAGO A CADEMARIO', '#0001', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80', ARRAY['Vendita']::text[], 'Disponibile', 'Si', 'In Esclusiva', 'RF-Cademario-1024.pdf', 3450000, 0, 'No', 0, 'Via Cantonale 45', 'Cademario', 6936, 'Svizzera', 'Casa', ARRAY['Villa']::text[], 320, 380, 6.5, 4, 2018, 202400, 1, 1, 'Stupenda villa minimalista con piscina a sfioro riscaldata, esposizione solare ottimale e vista mozzafiato a 180 gradi sul Lago di Lugano.', 2, 1, 'OLGA HONCHAR', '2026-05-26', 'MASSIMILIANO BOLDI',
 'planimetria-cademario.pdf', '1234', ARRAY['Primaria', 'Secondaria']::text[], 'Si',
 'Si', 'estratto-cademario.pdf',
 'Si', 'descrittivo-cademario.pdf',
 'No', NULL,
 NULL,
 'Si', 'assicurazione-cademario.pdf',
 'No', NULL,
 'No', NULL,
 'Si', 'stima-cademario.pdf',
 'No', NULL,
 'Si', 'rasi-cademario.pdf',
 'No', NULL),
(102, 'PRESTIGIOSO 3.5 LOCALI CON FINITURE DI ALTO STANDING', '#0006', 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80', ARRAY['Affitto']::text[], 'Disponibile', 'Si', 'Non in Esclusiva', 'RF-Paradiso-411.pdf', 0, 3100, 'Si', 150, 'Via San Salvatore 12', 'Paradiso', 6900, 'Svizzera', 'Appartamento', ARRAY['Appartamento']::text[], 110, 125, 3.5, 2, 2021, 0, 1, 0, 'Elegante appartamento situato a pochi passi dal lungolago. Dotato di domotica integrata, riscaldamento a pavimento e cantina vinicola privata.', 2, 1, 'OLGA HONCHAR', '2026-05-12', 'OLGA HONCHAR',
 'planimetria-paradiso.pdf', '5678', ARRAY['Primaria']::text[], 'Si',
 'Si', 'estratto-paradiso.pdf',
 'Si', 'descrittivo-paradiso.pdf',
 'Si', 'regolamento-paradiso.pdf',
 'spese-paradiso.pdf',
 'Si', 'assicurazione-paradiso.pdf',
 'Si', 'verbale-paradiso.pdf',
 'Si', 'fondo-paradiso.pdf',
 'No', NULL,
 'Si', 'assegnazione-paradiso.pdf',
 'No', NULL,
 'No', NULL),
(103, 'ESCLUSIVO APPARTAMENTO CON PISCINA E GIARDINO VISTA LAGO', '#0007', 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80', ARRAY['Vendita']::text[], 'In Trattativa', 'Si', 'In Esclusiva', 'RF-Bissone-902.pdf', 2850000, 0, 'Si', 0, 'Via Riviera 8', 'Bissone', 6816, 'Svizzera', 'Appartamento', ARRAY['Appartamento', 'Duplex']::text[], 240, 325, 5.5, 4, 2015, 202300, 1, 1, 'Meravigliosa proprietà bilivello con giardino privato pianeggiante, terrazza panoramica e accesso directo alla darsena condominiale.', 2, 1, 'MASSIMILIANO BOLDI', '2026-05-20', 'OLGA HONCHAR',
 'planimetria-bissone.pdf', '9012', ARRAY['Secondaria']::text[], 'No',
 'Si', 'estratto-bissone.pdf',
 'No', NULL,
 'Si', 'regolamento-bissone.pdf',
 'spese-bissone.pdf',
 'Si', 'assicurazione-bissone.pdf',
 'Si', 'verbale-bissone.pdf',
 'Si', 'fondo-bissone.pdf',
 'Si', 'stima-bissone.pdf',
 'Si', 'assegnazione-bissone.pdf',
 'Si', 'rasi-bissone.pdf',
 'Si', 'radon-bissone.pdf');

SELECT setval(pg_get_serial_sequence('public.immobili', 'id'), COALESCE(MAX(id), 1)) FROM public.immobili;

-- SEED DATA: VISITE
INSERT INTO public.visite (id, immobile_id, data_ora, tipo_visita, esito, feedback, cliente_id, partecipanti, creato_da) OVERRIDING SYSTEM VALUE VALUES
(30, 102, '2026-05-12T10:00:00+02:00', 'Shooting Fotografico', 'NEUTRO', 'Realizzazione dello shooting fotografico d''interni ed esterni completata con successo.', 4, 'Olga Honchar, Massimiliano Boldi, Stefano Cau', 'MASSIMILIANO BOLDI'),
(31, 103, '2026-05-12T13:00:00+02:00', 'Shooting Fotografico', 'NEUTRO', 'Foto aeree tramite drone per valorizzare la vista lago e la terrazza rooftop.', 4, 'Olga Honchar, Stefano Cau', 'MASSIMILIANO BOLDI'),
(32, 101, '2026-06-18T15:30:00+02:00', 'Visita Cliente', 'POSITIVO', 'Il cliente è rimasto entusiasta della zona giorno e della vista. Ha richiesto planimetria e rasi.', 5, 'Olga Honchar, Julio Kogan Amaro', 'OLGA HONCHAR');

SELECT setval(pg_get_serial_sequence('public.visite', 'id'), COALESCE(MAX(id), 1)) FROM public.visite;

-- AUDIT LOGS FOR PROPERTIES
CREATE TABLE IF NOT EXISTS public.immobili_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    immobile_id bigint REFERENCES public.immobili(id) ON DELETE CASCADE,
    descrizione text NOT NULL,
    utente text NOT NULL,
    data_ora timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

