-- ========================================================
-- HOMELAB CRM - DATABASE SCHEMA & INITIAL SEED DATA
-- ========================================================
-- Run this script in the Supabase SQL Editor (https://supabase.com)
-- to create the necessary tables and populate them with the initial mockup data.

-- 1. CLEANUP (Drop tables if they already exist - order matters because of foreign keys)
DROP TABLE IF EXISTS visite CASCADE;
DROP TABLE IF EXISTS immobili CASCADE;
DROP TABLE IF EXISTS contatti CASCADE;

-- 2. CREATE TABLE: CONTATTI (Anagrafica clienti, agenti, proprietari)
CREATE TABLE contatti (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cognome text NOT NULL,
    nome text NOT NULL,
    societa text,
    ruolo text NOT NULL,
    telefono text,
    mail text,
    note text,
    created_at timestamptz DEFAULT now()
);

-- 3. CREATE TABLE: IMMOBILI (Portafoglio immobiliare)
CREATE TABLE immobili (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome text NOT NULL,
    codice text,
    stato text NOT NULL DEFAULT 'Attivo',
    immobile_in text NOT NULL DEFAULT 'Vendita',
    mandato_firmato boolean NOT NULL DEFAULT false,
    tipo_mandato text,
    prezzo_vendita numeric NOT NULL DEFAULT 0,
    prezzo_affitto numeric NOT NULL DEFAULT 0,
    indirizzo text NOT NULL,
    comune text NOT NULL,
    npa text NOT NULL,
    nazione text NOT NULL DEFAULT 'Svizzera',
    categoria text NOT NULL,
    tipo text,
    superficie_abitabile numeric NOT NULL DEFAULT 0,
    superficie_sul numeric NOT NULL DEFAULT 0,
    locali text,
    bagni text,
    anno integer NOT NULL DEFAULT 0,
    rinnovo integer NOT NULL DEFAULT 0,
    garage boolean NOT NULL DEFAULT false,
    parcheggio boolean NOT NULL DEFAULT false,
    mappale text,
    lafe boolean NOT NULL DEFAULT false,
    rasi boolean NOT NULL DEFAULT false,
    radon boolean NOT NULL DEFAULT false,
    descrizione text,
    proprietario_id bigint REFERENCES contatti(id) ON DELETE SET NULL,
    agente_id bigint REFERENCES contatti(id) ON DELETE SET NULL,
    tipo_residenza text,
    estratto_registro_fondiario text,
    descrittivo_tecnico text,
    regolamento_condominiale text,
    spese_condominiali numeric NOT NULL DEFAULT 0,
    assicurazione_stabile text,
    verbale_ultima_assemblea text,
    fondo_rinnovamento numeric NOT NULL DEFAULT 0,
    valore_di_stima numeric NOT NULL DEFAULT 0,
    piano_assegnazioni text,
    fotografie text,
    link_cartella_doc text,
    note_interne text,
    creato_da text,
    ultima_modifica_il date DEFAULT CURRENT_DATE,
    ultima_modifica_fatta_da text,
    planimetria text,
    created_at timestamptz DEFAULT now()
);

-- 4. CREATE TABLE: VISITE (Attività di calendario, sopralluoghi, visite)
CREATE TABLE visite (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    immobile_id bigint REFERENCES immobili(id) ON DELETE CASCADE,
    data_ora timestamptz NOT NULL,
    tipo_visita text NOT NULL,
    esito text NOT NULL DEFAULT 'NEUTRO',
    feedback text,
    cliente_id bigint REFERENCES contatti(id) ON DELETE SET NULL,
    partecipanti text,
    creato_da text,
    created_at timestamptz DEFAULT now()
);

-- 5. SEED DATA: CONTATTI
INSERT INTO contatti (id, cognome, nome, societa, ruolo, telefono, mail, note) OVERRIDING SYSTEM VALUE VALUES
(1, 'Honchar', 'Olga', 'HOME LAB Real Estate Sagl', 'Agente Immobiliare', '+41 79 533 74 19', 'o.honchar@homelabrealestate.ch', 'Agente principale di riferimento per le proprietà di alto standing a Lugano.'),
(2, 'Iannone', 'Andrea', '', 'Proprietario, Locatore', '+41 76 458 29 29', 'a.iannone@exclusive-properties.ch', 'Proprietario dell''appartamento esclusivo con piscina a Bissone.'),
(3, 'Boldi', 'Massimiliano', 'HOME LAB Real Estate Sagl', 'Intermediario', '+41 79 457 95 58', 'm.boldi@homelabrealestate.ch', 'Gestore delle relazioni con i clienti e procacciatore d''affari.'),
(4, 'Cau', 'Stefano', 'Design Addict', 'Fotografo', '+41 76 526 28 82', 'studio@designaddict.ch', 'Fotografo professionista specializzato in architettura d''interni e video droni.'),
(5, 'Kogan Amaro', 'Julio', '', 'Cliente', '+41 78 991 12 23', 'j.kogan@vip-invest.ch', 'Potenziale acquirente interessato ad attici di lusso con vista lago.');

-- Reset identity sequence for contatti
SELECT setval(pg_get_serial_sequence('contatti', 'id'), COALESCE(MAX(id), 1)) FROM contatti;

-- 6. SEED DATA: IMMOBILI
INSERT INTO immobili (id, nome, codice, stato, immobile_in, mandato_firmato, tipo_mandato, prezzo_vendita, prezzo_affitto, indirizzo, comune, npa, nazione, categoria, tipo, superficie_abitabile, superficie_sul, locali, bagni, anno, rinnovo, garage, parcheggio, mappale, lafe, rasi, radon, descrizione, proprietario_id, agente_id, tipo_residenza, estratto_registro_fondiario, descrittivo_tecnico, regolamento_condominiale, spese_condominiali, assicurazione_stabile, verbale_ultima_assemblea, fondo_rinnovamento, valore_di_stima, piano_assegnazioni, fotografie, link_cartella_doc, note_interne, creato_da, ultima_modifica_il, ultima_modifica_fatta_da, planimetria) OVERRIDING SYSTEM VALUE VALUES
(101, '#0001-ESCLUSIVA PROPRIETÀ VISTA LAGO A CADEMARIO', '1', 'Attivo', 'Vendita', true, 'Esclusiva', 3450000, 0, 'Via Cantonale 45', 'Cademario', '6936', 'Svizzera', 'Villa', 'Moderno', 320, 380, '6.5', '4', 2018, 2024, true, true, '1024', true, true, false, 'Stupenda villa minimalista con piscina a sfioro riscaldata, esposizione solare ottimale e vista mozzafiato a 180 gradi sul Lago di Lugano.', 2, 1, 'Secondaria ammessa', 'RF-Cademario-1024.pdf', 'DT-Cademario-Completo.pdf', '', 0, 'ECA Ticino - CHF 1''200/anno', '', 0, 3100000, 'Piano_Posteggi_Cademario.pdf', 'https://homelab.ch/foto-cademario', 'https://dropbox.com/homelab/cademario', 'Trattativa riservata. Verificare disponibilità LAFE prima di procedere.', 'OLGA HONCHAR', '2026-05-26', 'MASSIMILIANO BOLDI', ''),
(102, '#0006-PRESTIGIOSO 3.5 LOCALI CON FINITURE DI ALTO STANDING', '6', 'Attivo', 'Affitto', true, 'Semi-Esclusiva', 0, 3100, 'Via San Salvatore 12', 'Paradiso', '6900', 'Svizzera', 'Appartamento', 'Moderno', 110, 125, '3.5', '2', 2021, 0, true, false, '411', true, true, true, 'Elegante appartamento situato a pochi passi dal lungolago. Dotato di domotica integrata, riscaldamento a pavimento e cantina vinicola privata.', 2, 1, 'Solo Primaria', 'RF-Paradiso-411.pdf', '', 'Regolamento_Condo_Paradiso_2021.pdf', 450, 'Assicurazione Stabile Allianz', 'Verbale_Assemblea_Paradiso_2025.pdf', 15000, 0, '', 'https://homelab.ch/foto-paradiso', 'https://dropbox.com/homelab/paradiso', 'Inquilino attuale lascia a fine settembre 2026. Preavviso visite 48h.', 'OLGA HONCHAR', '2026-05-12', 'OLGA HONCHAR', ''),
(103, '#0007-ESCLUSIVO APPARTAMENTO CON PISCINA E GIARDINO VISTA LAGO', '7', 'In trattativa', 'Vendita', true, 'Esclusiva', 2850000, 0, 'Via Riviera 8', 'Bissone', '6816', 'Svizzera', 'Appartamento', 'Duplex', 240, 325, '5.5', '4', 2015, 2023, true, true, '902', false, true, false, 'Meravigliosa proprietà bilivello con giardino privato pianeggiante, terrazza panoramica e accesso directo alla darsena condominiale.', 2, 1, 'Secondaria ammessa', 'RF-Bissone-902.pdf', 'Descrittivo_Bissone_2015.pdf', 'Regolamento_Bissone.pdf', 800, 'Generali Stabili', 'Verbale_2025_Bissone.pdf', 45000, 2600000, 'Assegnazione_Posti_Auto_Darsena.pdf', 'https://homelab.ch/foto-bissone', 'https://dropbox.com/homelab/bissone', 'Offerta in corso a CHF 2''700''000 da parte di cliente estero.', 'MASSIMILIANO BOLDI', '2026-05-20', 'OLGA HONCHAR', '');

-- Reset identity sequence for immobili
SELECT setval(pg_get_serial_sequence('immobili', 'id'), COALESCE(MAX(id), 1)) FROM immobili;

-- 7. SEED DATA: VISITE
INSERT INTO visite (id, immobile_id, data_ora, tipo_visita, esito, feedback, cliente_id, partecipanti, creato_da) OVERRIDING SYSTEM VALUE VALUES
(30, 102, '2026-05-12T10:00:00+02:00', 'Shooting Fotografico', 'NEUTRO', 'Realizzazione dello shooting fotografico d''interni ed esterni completata con successo.', 4, 'Olga Honchar, Massimiliano Boldi, Stefano Cau', 'MASSIMILIANO BOLDI'),
(31, 103, '2026-05-12T13:00:00+02:00', 'Shooting Fotografico', 'NEUTRO', 'Foto aeree tramite drone per valorizzare la vista lago e la terrazza rooftop.', 4, 'Olga Honchar, Stefano Cau', 'MASSIMILIANO BOLDI'),
(32, 101, '2026-06-18T15:30:00+02:00', 'Visita Cliente', 'POSITIVO', 'Il cliente è rimasto entusiasta della zona giorno e della vista. Ha richiesto planimetria e rasi.', 5, 'Olga Honchar, Julio Kogan Amaro', 'OLGA HONCHAR');

-- Reset identity sequence for visite
SELECT setval(pg_get_serial_sequence('visite', 'id'), COALESCE(MAX(id), 1)) FROM visite;
